ads/ads_app/urls.py
from django.urls import path

from .views import (
    AdListView,
    AdCreateView,
    AdUpdateView,
    AdDeleteView,
    ExchangeProposalCreateView,
    ExchangeProposalListView,
)

urlpatterns = [
    path("", AdListView.as_view(), name="ads-list"),
    path("add/", AdCreateView.as_view(), name="ads-create"),
    path("update/<int:pk>", AdUpdateView.as_view(), name="ads-update"),
    path("delete/<int:pk>/", AdDeleteView.as_view(), name="ads-delete"),
    path("add_ex_pr/", ExchangeProposalCreateView.as_view(), name="ads-expr-create"),
    path("exchange_proposals/", ExchangeProposalListView.as_view(), name="ads-exprs"),
]

ads/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from ads_app.routes import router

urlpatterns = [
    path("", include(("ads_app.urls", "ads_app"), namespace="ads_app")),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)),
    path("admin/", admin.site.urls),
]

urlpatterns += [
    path("accounts/", include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ads/ads_app/models.py
"""Модели приложения ads_app"""

from django.contrib.auth.models import User
from django.db import models


class Ad(models.Model):
    """Модель товаров"""

    CHOICES = (
        ("n", "новый"),
        ("d", "уцененный"),
        ("u", "б/у"),
    )

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="пользователь"
    )
    title = models.CharField(max_length=100, verbose_name="название товара")
    description = models.TextField(verbose_name="описание товара")
    image = models.ImageField(
        upload_to="images/%Y/%m/%d/", null=True, blank=True, verbose_name="изображение"
    )
    category = models.CharField(max_length=100, verbose_name="категория товара")
    condition = models.CharField(
        max_length=50, choices=CHOICES, verbose_name="состояние товара"
    )
    created_at = models.DateTimeField(
        auto_now_add=True, editable=False, verbose_name="время создания товара"
    )

    class Meta:
        verbose_name = "товар"
        verbose_name_plural = "товары"
        ordering = ("-created_at",)

    def __str__(self):
        return self.title


class ExchangeProposal(models.Model):
    """Модель обменов"""

    CHOICES = (
        ("w", "ожидает"),
        ("a", "принято"),
        ("r", "отклонено"),
    )

    ad_sender = models.ForeignKey(
        Ad,
        on_delete=models.CASCADE,
        related_name="ad_senders",
        verbose_name="предлагаемый товар",
    )
    ad_receiver = models.ForeignKey(
        Ad,
        on_delete=models.CASCADE,
        related_name="ad_receivers",
        verbose_name="ожидаемый товар",
    )
    comment = models.TextField(verbose_name="комментарий")
    status = models.CharField(
        max_length=50, choices=CHOICES, verbose_name="статус предложения"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        editable=False,
        verbose_name="время создания предложения обмена",
    )

    class Meta:
        verbose_name = "предложение обмена"
        verbose_name_plural = "предложения обмена"
        ordering = ("-created_at",)

    def __str__(self):
        return f"Обмен {self.ad_sender} на {self.ad_receiver}"

ads/ads_app/routes.py
from rest_framework import routers

from ads_app.apiviews import AdViewSet

router = routers.DefaultRouter()
router.register('ads', AdViewSet, basename='ad')

ads/ads_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView
from django_filters.views import FilterView

from ads_app.filters import AdFilter, ExchangeProposalFilter
from ads_app.models import Ad, ExchangeProposal
from ads_app.services import get_full_path_of_request_without_param_page, have_user_ads


class AdListView(FilterView):
    """Представление для отображения списка всех товаров"""

    template_name = "ads_list.html"
    model = Ad
    filterset_class = AdFilter
    context_object_name = "ads"
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        relative_url = get_full_path_of_request_without_param_page(self.request)
        context["is_params"] = relative_url[1]
        context["cur_url"] = relative_url[0]
        context["have_user_ads"] = have_user_ads(self.request)
        return context


class AdCreateView(LoginRequiredMixin, CreateView):
    template_name = "create.html"
    model = Ad
    fields = ["title", "description", "category", "condition", "image"]
    success_url = "/ads/"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class AdUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "ad_update.html"
    model = Ad
    fields = ["title", "description", "category", "condition", "image"]
    success_url = "/ads/"


class AdDeleteView(DeleteView):
    model = Ad
    context_object_name = "ad"
    success_url = reverse_lazy("ads_app:ads-list")
    template_name = "ad_confirm_delete.html"


class ExchangeProposalCreateView(LoginRequiredMixin, CreateView):
    template_name = "exchange_proposal_create.html"
    model = ExchangeProposal
    fields = ["ad_sender", "ad_receiver", "comment"]
    success_url = "/ads/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"].fields["ad_sender"].queryset = Ad.objects.filter(
            user=self.request.user
        )
        context["form"].fields["ad_receiver"].queryset = Ad.objects.exclude(
            user=self.request.user
        )
        return context

    def form_valid(self, form):
        form.instance.status = "w"
        return super().form_valid(form)


class ExchangeProposalListView(LoginRequiredMixin, FilterView):
    """Представление для отображения списка всех предложений пользователя"""

    template_name = "expr_list.html"
    model = ExchangeProposal
    filterset_class = ExchangeProposalFilter
    context_object_name = "exproposals"
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        relative_url = get_full_path_of_request_without_param_page(self.request)
        context["is_params"] = relative_url[1]
        context["cur_url"] = relative_url[0]
        context["have_user_ads"] = have_user_ads(self.request)
        return context

    def form_valid(self, form):
        status = form.instance.status
        ep_id = form.instance.ep_id
        ep = ExchangeProposal.objects.get(id=int(ep_id))
        if status == "accept":
            ep.status = "принято"
        elif status == "reject":
            ep.status = "отклонено"
        ep.save()
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        status = request.POST.get("status")
        ep_id = request.POST.get("ep_id")

        ep = ExchangeProposal.objects.get(id=int(ep_id))
        if status == "accept":
            ep.status = "a"
        elif status == "reject":
            ep.status = "r"
        ep.save()
        return HttpResponseRedirect(reverse("ads_app:ads-exprs"))

ads/templates/ad_confirm_delete.html
{%extends 'base.html'%}

{%block content%}
<div class="center">
	<form method="post" class="card">
		{% csrf_token %}
		<h2>Удаление товара</h2>
		<p>Вы действительно хотите удалить товар "{{ad}}"?</p>
		<p class="form-buttons">
			<input type="submit" class="btn btn-primary" value="Удалить">
			<a href="{% url 'ads_app:ads-list'%}" class="btn btn-outline">Отмена</a>
		</p>
	</form>
</div>

{%endblock content%}

ads/templates/ad_update.html
{% extends 'base.html' %}

{% block title %} Редактирование товара {% endblock %}

{% block content %}
 <form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

ads/templates/ads_list.html
{% extends 'base.html' %}

{% block title %}Список товаров{% endblock %}
{% block content %}

    {% if have_user_ads %}
    <a href="{% url 'ads_app:ads-expr-create' %}">
       <p>Создать обменное предложение</p>
    </a>
    {% endif %}

<h2>Параметры фильтрации</h2>
<form method="get">
    {{ filter.form.as_p }}
    <input type="submit" />
</form>
<h2>Список товаров</h2>
 <div>
     <ul>
         {% for ad in ads %}
            <li>
                <h3>Название товара: {{ ad.title }}</h3>
                <p>Описание товара: {{ ad.description }}</p>
                <p>Автор публикации: {{ ad.user }}</p>
                <p>Категория товара: {{ ad.category }}</p>
                <p>Статус товара: {{ ad.get_condition_display }}</p>
                <p>Дата создания публикации: {{ ad.created_at }}</p>
                {% if ad.image %}
                    <div>
                       <img src="{{ ad.image.url }}" alt="{{ ad.title }}" width="300">
                    </div>
                {% endif %}
                {% if request.user == ad.user %}
                <a href="{% url 'ads_app:ads-update' pk=ad.id %}">
                   <p>Редактировать</p>
                </a>
                <a href="{% url 'ads_app:ads-delete' pk=ad.id %}">
                   <p>Удалить</p>
                </a>
                {% endif %}
                </li>
         {% endfor %}
     </ul>
 </div>


{% if ads %}
    <div>
        {% for p in paginator.page_range %}
           {% if page_obj.number == p %}
                <a href="#"><span style="margin-right: 10px"><strong>{{ p }}</strong></span></a>
           {% else %}
                {% if is_params %}
                     <a href="{{ cur_url }}&page={{ p }}"><span style="margin-right: 10px">{{ p }}</span></a>
                {% else %}
                     <a href="?page={{ p }}"><span style="margin-right: 10px">{{ p }}</span></a>
                {% endif %}
           {% endif %}
        {% endfor %}
    </div>
{% endif %}
{% endblock %}

ads/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="{{ _('Описание страницы') }} ">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
    </head>
    <body>

        <header>
            <a href="{% url 'ads_app:ads-list' %}">
                   <p>На главную</p>
            </a>
            {% if request.user.is_authenticated %}
               <a href="{% url 'ads_app:ads-create' %}">
                   <p>Добавить товар</p>
               </a>
                   <a href="{% url 'ads_app:ads-exprs' %}">
                   <p>Текущие предложения</p>
               </a>
               <a href="{% url 'logout' %}">
                   <p>Выйти</p>
               </a>
            {% else %}
                <a href="{% url 'login' %}">
                <p>Войти</p>
                </a>

            {% endif %}
        </header>

        <div>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

ads/templates/create.html
{% extends 'base.html' %}

{% block title %} Создание товара {% endblock %}

{% block content %}
 <form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

ads/templates/exchange_proposal_create.html
{% extends 'base.html' %}

{% block title %} Создание предложения для обмена {% endblock %}

{% block content %}
 <form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

ads/templates/expr_list.html
{% extends 'base.html' %}

{% block title %} Список предложений {% endblock %}

{% block content %}
<h2>Параметры фильтрации</h2>
<form method="get">
    {{ filter.form.as_p }}
    <input type="submit" />
</form>
<h2>Список предложений</h2>
 <div>
     <ul>
         {% for ep in exproposals %}
            <li>
                <h3>Предложенный товар: {{ ep.ad_sender }}</h3>
                <p>Требуемый товар: {{ ep.ad_receiver }}</p>
                <p>Инициатор предожения: {{ ep.ad_sender.user }}</p>
                <p>Комментарий: {{ ep.comment }}</p>
                <p>Статус товара: {{ ep.get_status_display }}</p>
                <p>Дата создания предложения: {{ ep.created_at }}</p>
                {% if ep.status == "w" and ep.ad_sender.user == request.user %}
                <form method = "POST">
                    {% csrf_token %}
                    <input type="hidden" id="ep_id" name="ep_id" value="{{ep.id}}" />
                    <button type="submit" value="accept" name="status">Принять</button>
                    <button type="submit" value="reject" name="status">Отклонить</button>
                </form>
                {% endif %}
                </li>
         {% endfor %}
     </ul>
 </div>


{% if exproposals %}
    <div>
        {% for p in paginator.page_range %}
           {% if page_obj.number == p %}
                <a href="#"><span style="margin-right: 10px"><strong>{{ p }}</strong></span></a>
           {% else %}
                {% if is_params %}
                     <a href="{{ cur_url }}&page={{ p }}"><span style="margin-right: 10px">{{ p }}</span></a>
                {% else %}
                     <a href="?page={{ p }}"><span style="margin-right: 10px">{{ p }}</span></a>
                {% endif %}
           {% endif %}
        {% endfor %}
    </div>
{% endif %}
{% endblock %}